---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - SHoogland
  - package-ecosystem: "rubygems"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - SHoogland