default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
    api_key = app_store_connect_api_key(
      key_id: "BMN257SNP2",
      issuer_id: "d1b9b805-0e05-4810-963b-c213ee353573",
      key_filepath: "./AuthKey.p8",
      duration: 1200, # optional (maximum 1200)
    )

    version = get_version_number(xcodeproj: "timmerdorp.xcodeproj")

    build_num = app_store_build_number(
      api_key: api_key,
      version: version,
      live: false,
      initial_build_number: 0,
    )

    increment_build_number(
      build_number: build_num + 1
    )    

    decode_file

    keychain_password = SecureRandom.uuid
    keychain_name = 'ios-build.keychain'

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: 'ios-build.p12',
      certificate_password: '',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      log_output: true
    )

    @profiles.each { |profile| install_provisioning_profile(path: profile) }

    update_project_provisioning(
      xcodeproj: "timmerdorp.xcodeproj",
      profile: @profiles[0],
    )

    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

    build_app(scheme: "timmerdorp")

    upload_to_testflight(
      api_key: api_key,
      notify_external_testers: false,
    )
    
  end

  def decode_file
    File.write('../ios-build.p12', Base64.decode64(ENV['P12_BASE64']))
    @profiles = []
    ENV['MOBILEPROVISION_BASE64'].split(/\R/).each.with_index(
      1
    ) do |profile, index|
      filename = "ios-build-#{index}.mobileprovision"
      puts "creating ../#{filename}"
      File.write("../#{filename}", Base64.decode64(profile))
      @profiles.push(filename)
    end
  end

end
